# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d42fdb3241729adfabe3dd2eadecc1deb80e9f246d368b0324c963fbe5b962b1da76fa85f42d20f5f9935ac8750c4ce97c22d8e1330392b2de3402f2b7ae19

test:
  secret_key_base: 833eb652bc752cf6ca44b7b7f918b2b0fa8b39531d4b2736c2185d180a47da07d518340308f10c9d1865289d49bd1a1260f396c9f63257aa212f3f8e73d6b397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
